### ISSUE TITLE
Control mono envelope peak?

### ISSUE THREAD

**Issue by yentzee** [MCUdude/SigmaDSP#10]
Hi, 
is there any way to control the mono envelope peak block? There isnt any function for ot I believe.
Cheers,
Jens

**Comment by MCUdude** [comment]
You can control whatever block you like, even though this library doesn't support the block directly.

Figure out how the block works in the SigmaStudio capture window, and use
`dsp.safeload_write(startMemoryAddress, data1, data2, ..., dataN);`

`safeload_write` is template-based, so you can have as few or as many parameters as you want.

**Comment by yentzee** [comment]
Awesome, thanks for your help and the fast response 👍
