### ISSUE TITLE
Implementing custom crossovers 

### ISSUE THREAD

**Issue by curtis-j-campbell** [MCUdude/SigmaDSP#21]
Hi, 

I've recently come across this library and it seems to be the ideal tool for attempting to create a hardware controlled variable cross over however I've been struggling to understand how I would go about implementing these blocks (see attached image) in code. My aim is to have an input split and then fed through 4 cross overs and have 4 outputs at the end

The generated dsp params file (zipped and attached below ) is a lot more complicated compared to the examples and Im not quite sure how to go about feeding one filter into another (cascading them). 

Is anyone able to offer any help as to how I can implement my sigma studio project using this library? Is there a simpler way to achieve my objective with different sigma studio blocks? 

Thanks in advance

![image](https://user-images.githubusercontent.com/52332474/136652982-b6e4d3e5-7f32-4d33-9d6c-f6bb5c6a903d.png)

[SigmaDSP_parameters.zip](https://github.com/MCUdude/SigmaDSP/files/7315333/SigmaDSP_parameters.zip))

**Comment by MCUdude** [comment]
If you can live with second-order filters, you can actually use the 2nd order EQ algorithm! I haven't tested this exact code, but I've used the exact same filter block as you do, only with 2nd order filters.

Figuring out algorithms yourself can be a bit time-consuming. Most of the algorithms in SigmaStudio aren't proprietary, but they are still closed-source and have to be reverse-engineered. There is a lot of resources on the Analog Devices forum on how you can do this. This library is just a versatile tool that lets you quite easily interface with your DSP from a microcontroller once you have a working algorithm. If you want a simple challenge, try reverse-engineering the volume slew slider and see if you can get the same algorithm as [this library uses](https://github.com/MCUdude/SigmaDSP/blob/f2a7be955a124bddbd94d2342afc2514b9276a07/src/SigmaDSP.cpp#L154-L167). Use the output in the SigmaStudio capture window.

There are also simpler algorithms you can crack such as muxes/demuxes or the linear gain block.

```c++
// Create struct object for a filter
secondOrderEQ filter;

//...

// Use ::lowpass or ::highpass
filter.filterType = parameters::filterType::lowpass;

// Filter frequency 100Hz
filter.freq = 100;

// Q value 0.7071 used by Sigma Studio
filter.Q = 0.7071;

dsp.EQsecondOrder(MOD_NFILTER1_ALG0_STAGE3_NTHORDERDOUBLE1_0B_1_ADDR, filter);

```

**Comment by curtis-j-campbell** [comment]
Hi MCUdude, appreciate the advice, I am definitely going to switch over to 2nd order filters and experiment with those. I have been looking a

**Comment by curtis-j-campbell** [comment]
Thanks for clarifying that
