### ISSUE TITLE
Crossover

### ISSUE THREAD

**Issue by rudiars** [MCUdude/SigmaDSP#22]
hi, I need help how to control ADAU1701 crossover ?
thanks for respond..

**Comment by MCUdude** [comment]
There are several crossovers. Which are you thinking about?

**Comment by rudiars** [comment]
I need 2nd order 3 way crossover sir, thanks for respond

**Comment by rudiars** [comment]
please help...

**Comment by MCUdude** [comment]
Why not just use three 2nd order filters, and control each of them individually?

**Comment by djamps** [comment]
@MCUdude hey dude!   Any chance to control Nth order 1 channel filters?   2nd order isn't quite enough for my application.   Thanks again for your awesome work!

**Comment by MCUdude** [comment]
@djamps Everything can be controlled, but you'll have to figure out the algorithm yourself, since this library currently doesn't support it. If you don't want to go down that rabbit hole, you can always just connect two 2nd order filters in series.

**Comment by djamps** [comment]
If it helps anyone, here's a trick to have adjustable crossovers without having to reverse engineer the algo:
https://ez.analog.com/dsp/sigmadsp/f/q-a/64925/sure-dsp---crossover-function
