### ISSUE TITLE
Pin connections

### ISSUE THREAD

**Issue by darwin1234** [MCUdude/SigmaDSP#30]
Hi,

I am looking to this repo. I don’t see any  images to connect those two devices. Is it available?

Thanks

**Comment by MCUdude** [comment]
This library only supports i2c communication with the DSP, so wire it like shown in the datasheet:

https://www.analog.com/media/en/technical-documentation/data-sheets/adau1701.pdf

<img width="610" alt="image" src="https://user-images.githubusercontent.com/3238730/181347779-557dd152-449a-4409-ad98-8d2aaf16e694.png">
