### ISSUE TITLE
Use 2 output ADAU1701

### ISSUE THREAD

**Issue by Thread09** [MCUdude/SigmaDSP#31]
Hi,

I'm using an ADAU1701 and I can't find how to set different parameters on output 1 and output 2.

Do I need to use writeRegister or something is already develop ?

Thanks

**Comment by MCUdude** [comment]
> I'm using an ADAU1701 and I can't find how to set different parameters on output 1 and output 2.

What are you trying to achieve? What parameters do you want to set? You can do all permanent settings in SigmaStudio, and it will be present when you export the project.

**Comment by MCUdude** [comment]
>  I want to set different parameters (like band pass, volume, ..) for output 1 and output 2.

See the screenshot below. You don't make any changes to the output blocks themselves. You connect various blocks to them.

The screenshot below is for an amplifier that takes a mono signal as input. Output 0 and 1 are for a speaker amplifier, and output 3 and 4 are for a headphone amplifier.

You should play around with SigmaStudio and get familiar with it. This library is designed to tweak the parameters of the blocks you've pulled into your SigmaStudio program.

![image](https://user-images.githubusercontent.com/3238730/182368617-469b3bb7-8c72-481f-91e8-8c0445b7e1e7.png)
