### ISSUE TITLE
ESP32-C3

### ISSUE THREAD

**Issue by Trylan** [MCUdude/SigmaDSP#34]
Hi is this library compatible with an ESP32-C3? Would like to control sigma studio parameters on an ADAU1701 through Bluetooth.

Additionally, does this library support changing FIR filter coefficients?
Thanks!

**Comment by MCUdude** [comment]
It should be! The library is generic and relies only on the Arduino Wire library. There's no platform-specific code in there.

**Comment by Trylan** [comment]
Great! Thank you for your response. Are there methods for reading and changing FIR filter coefficients?
